name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-jwt-rbac:latest .

      - name: Push Docker image to Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-jwt-rbac:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-jwt-rbac \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-jwt-rbac:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }}
